### ISSUE TITLE
VideoMediaset Installation failed.........

### ISSUE THREAD

**Issue by DjDiabolik** [FusionwareIT/Repository-FusionBox#1]
I have tryed to install on OSMC latest on my Pi2 but the installation failed every time......... on LOG no info about this failed.

You can fix this ?

**Comment by alepsrt** [comment]
i'm working on... see here http://forum.kodi.tv/showthread.php?tid=184219

**Comment by DjDiabolik** [comment]
Yeah.......... subscript to this thread......... thanks.
